package repository
package repository


































































































}	return err	_, err := r.db.Exec(query, promotionID, orderID)	`		VALUES ($1, $2)		INSERT INTO promotion_usage (promotion_id, order_id)	query := `func (r *PromotionRepository) RecordUsage(promotionID string, orderID string) error {}	return count, err	err := r.db.QueryRow(query, promotionID).Scan(&count)	`		WHERE promotion_id = $1		FROM promotion_usage		SELECT COUNT(*)	query := `	var count int64func (r *PromotionRepository) CountUsage(promotionID string) (int64, error) {}	return &p, nil	}		return nil, err	if err != nil {	}		return nil, nil	if err == sql.ErrNoRows {	)		&p.MaxUsagePerCustomer, &p.IsActive, &p.CreatedAt, &p.UpdatedAt,		&p.ValidFrom, &p.ValidUntil, &p.MaxUsageCount,		&p.DiscountValue, &p.MaxDiscount, &p.MinOrderTotal,		&p.ID, &p.Code, &p.Name, &p.Description, &p.DiscountType,	err := r.db.QueryRow(query, id).Scan(	`		LIMIT 1		WHERE id = $1		FROM promotions		       created_at, updated_at		       max_usage_count, max_usage_per_customer, is_active,		       max_discount, min_order_total, valid_from, valid_until,		SELECT id, code, name, description, discount_type, discount_value,	query := `	var p model.Promotionfunc (r *PromotionRepository) GetByID(id string) (*model.Promotion, error) {}	return &p, nil	}		return nil, err	if err != nil {	}		return nil, nil	if err == sql.ErrNoRows {	)		&p.MaxUsagePerCustomer, &p.IsActive, &p.CreatedAt, &p.UpdatedAt,		&p.ValidFrom, &p.ValidUntil, &p.MaxUsageCount,		&p.DiscountValue, &p.MaxDiscount, &p.MinOrderTotal,		&p.ID, &p.Code, &p.Name, &p.Description, &p.DiscountType,	err := r.db.QueryRow(query, code).Scan(	`		LIMIT 1		WHERE code = $1 AND is_active = true		FROM promotions		       created_at, updated_at		       max_usage_count, max_usage_per_customer, is_active,		       max_discount, min_order_total, valid_from, valid_until,		SELECT id, code, name, description, discount_type, discount_value,	query := `	var p model.Promotionfunc (r *PromotionRepository) GetByCode(code string) (*model.Promotion, error) {}	return &PromotionRepository{db: db}func NewPromotionRepository(db *sql.DB) *PromotionRepository {}	db *sql.DBtype PromotionRepository struct {)	"github.com/navap/pointofsale/promotion-service/internal/model"	"time"	"database/sql"import (