package handler





































































}	c.JSON(http.StatusOK, gin.H{"status": "healthy"})func (h *PromotionHandler) Health(c *gin.Context) {}	c.JSON(http.StatusOK, gin.H{"status": "usage recorded"})	}		return		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to record usage"})		}			return			c.JSON(http.StatusConflict, gin.H{"error": "Promotion already used for this order"})		if err == sql.ErrNoRows {	if err != nil {	err := h.service.RecordUsage(req.PromotionID, req.OrderID)	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid request"})	if err := c.ShouldBindJSON(&req); err != nil {	}		OrderID     string `json:"order_id" binding:"required"`		PromotionID string `json:"promotion_id" binding:"required"`	var req struct {func (h *PromotionHandler) RecordUsage(c *gin.Context) {}	c.JSON(http.StatusOK, result)	result := h.service.ValidateAndEvaluate(req.PromotionCode, req.OrderTotal)	}		return		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid request"})	if err := c.ShouldBindJSON(&req); err != nil {	var req model.EvaluateRequestfunc (h *PromotionHandler) EvaluatePromotion(c *gin.Context) {}	router.GET("/health", h.Health)	}		api.POST("/record-usage", h.RecordUsage)		api.POST("/evaluate", h.EvaluatePromotion)	{	api := router.Group("/api/promotions")func (h *PromotionHandler) RegisterRoutes(router *gin.Engine) {}	return &PromotionHandler{service: service}func NewPromotionHandler(service *service.PromotionService) *PromotionHandler {}	service *service.PromotionServicetype PromotionHandler struct {)	"github.com/navap/pointofsale/promotion-service/internal/service"	"github.com/navap/pointofsale/promotion-service/internal/model"	"github.com/gin-gonic/gin"	"net/http"	"database/sql"import (package handler