package paymentservice





























































































}	_ = json.NewEncoder(w).Encode(payload)	w.WriteHeader(status)	w.Header().Set("Content-Type", "application/json")func writeJSON(w http.ResponseWriter, status int, payload any) {}	}		log.Fatalf("Server error: %v", err)	if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {	log.Printf("Payment service on port %s", port)	}()		server.Shutdown(context.Background())		<-sigch		signal.Notify(sigch, syscall.SIGTERM, syscall.SIGINT)		sigch := make(chan os.Signal, 1)	go func() {	}		Handler: router,		Addr:    fmt.Sprintf(":%s", port),	server := &http.Server{	}).Methods(http.MethodGet)		})			"status": "PENDING",			"id":     id,		writeJSON(w, http.StatusOK, map[string]any{		id := mux.Vars(r)["id"]	router.HandleFunc("/api/payments/{id}", func(w http.ResponseWriter, r *http.Request) {	}).Methods(http.MethodPost)		})			"amount":   req.Amount,			"status":   "CONFIRMED",			"order_id": req.OrderID,		writeJSON(w, http.StatusOK, map[string]any{		_ = json.NewDecoder(r.Body).Decode(&req)		var req CheckoutRequest	router.HandleFunc("/api/payments/checkout", func(w http.ResponseWriter, r *http.Request) {	}).Methods(http.MethodGet)		writeJSON(w, http.StatusOK, map[string]string{"status": "ok"})	router.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {	router := mux.NewRouter()	}		log.Fatalf("DB ping failed: %v", err)	if err := db.Ping(); err != nil {	defer db.Close()	}		log.Fatalf("DB connect failed: %v", err)	if err != nil {	db, err := sql.Open("postgres", dbURL)	}		dbURL = "postgres://user:password@localhost:5432/pointofsale"	if dbURL == "" {	dbURL := os.Getenv("DATABASE_URL")	}		port = "8085"	if port == "" {	port := os.Getenv("PORT")func main() {}	IdempotencyKey string  `json:"idempotency_key"`	PromotionCode  string  `json:"promotion_code"`	Amount         float64 `json:"amount"`	OrderID        string  `json:"order_id"`type CheckoutRequest struct {)	_ "github.com/lib/pq"	"github.com/gorilla/mux"	"syscall"	"os/signal"	"os"	"net/http"	"log"	"fmt"	"encoding/json"	"database/sql"	"context"import (package main